[versions]
agp = "8.13.0"
kotlin = "2.0.21"      # üëà PH·∫¢I c√≥ d√≤ng n√†y
compose = "1.7.4"
material3 = "1.3.0"
navCompose = "2.8.3"
room = "2.6.1"
retrofit = "2.11.0"
moshi = "1.15.1"
coil = "2.7.0"
okhttpLogging = "4.12.0"
activityCompose = "1.9.3"
browser = "1.9.0"   # activity-compose (kh√°c v·ªõi activity th∆∞·ªùng)

[libraries]
# Compose
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navCompose" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# Lifecycle
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.8.6" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "2.8.6" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Network
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttpLogging" }

# Images
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler    = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
